# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Snowex Hackweek
author: eScience Institute, University of Washington
logo: logo.png

parse:
  myst_substitutions:
    hackweek: snowex-hackweek
    dates: July 12 to 16, 2021
    github_org_url: https://github.com/snowex-hackweek
    jupyterhub_url: https://snowex.hackweek.io
    contact_email: [uwhackweek@github.com](mailto:uwhackweek@github.com)

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  binderhub_url: ''

# Information about where the book exists on the web
repository:
  url: https://github.com/snowex-hackweek/website
  path_to_book: book
  branch: main

# Bibliography
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year  # or label, super, \supercite

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-QM84T4SB76
