name: Test

on:
  pull_request:
    paths:
      - 'book/**'
      - '.github/workflows/test.yaml'
      - '.binder/**'
    branches:
      - main

env:
  DOCKER_IMAGE: uwhackweek/snowex:latest

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Ensure Clean Notebooks
      run: |
        pip install nb-clean==2.0.2
        find book -name "*ipynb" | xargs nb-clean check --preserve-cell-metadata

    - name: Pull Docker Image
      run: |
        docker pull $DOCKER_IMAGE
        docker images

    - name: Build JupyterBook
      run: |
        docker run -u root -v ${{ github.workspace }}:/home/jovyan:rw $DOCKER_IMAGE jb build book --warningiserror --keep-going

    - name: Save Build
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: book/_build/
